name: Deploy on Prod and Dev

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: copy files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        target: /root/backend-zacksys

    - name: SSH into remote server and run commands
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          TARGET_DIR="/root/explorer-backend-subql"           
          echo "Deploying"
          echo "Building Frontend"
          cd "$TARGET_DIR/frontend"
          ls
          export NVM_DIR="$HOME/.nvm"
          source $NVM_DIR/nvm.sh
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          npm ci
          npm run build
          echo "Deploying Backend"
          cd "$TARGET_DIR"
          docker compose -f docker-compose.prod.yml down --remove-orphans || true
          docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
          echo "End"
